/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyRouteImport } from './routes/weekly'
import { Route as VodsRouteImport } from './routes/vods'
import { Route as SnapshotRouteImport } from './routes/snapshot'
import { Route as RightsRouteImport } from './routes/rights'
import { Route as PlayRouteImport } from './routes/play'
import { Route as NoticeRouteImport } from './routes/notice'
import { Route as MultiviewRouteImport } from './routes/multiview'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as CafeRouteImport } from './routes/cafe'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VodsIndexRouteImport } from './routes/vods/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileCodeRouteImport } from './routes/profile/$code'
import { Route as PlayDiscoverRouteImport } from './routes/play/discover'
import { Route as PlayMemberRouteImport } from './routes/play/_member'
import { Route as PlayCatalogRouteImport } from './routes/play/_catalog'
import { Route as AdminYoutubeCacheRouteImport } from './routes/admin/youtube-cache'
import { Route as AdminSnapshotRouteImport } from './routes/admin/snapshot'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminOtwPlayRouteImport } from './routes/admin/otw-play'
import { Route as AdminOperationsRouteImport } from './routes/admin/operations'
import { Route as AdminNoticesRouteImport } from './routes/admin/notices'
import { Route as AdminMemberPostsRouteImport } from './routes/admin/member-posts'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminKirinukiRouteImport } from './routes/admin/kirinuki'
import { Route as AdminDdaysRouteImport } from './routes/admin/ddays'
import { Route as PlayCatalogIndexRouteImport } from './routes/play/_catalog/index'
import { Route as PlayMemberSubmitRouteImport } from './routes/play/_member/submit'
import { Route as PlayMemberSubmissionsRouteImport } from './routes/play/_member/submissions'
import { Route as PlayCatalogSongsRouteImport } from './routes/play/_catalog/songs'
import { Route as PlayCatalogSongsIndexRouteImport } from './routes/play/_catalog/songs/index'
import { Route as PlayCatalogSongsSongSlugRouteImport } from './routes/play/_catalog/songs/$songSlug'

const WeeklyRoute = WeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const VodsRoute = VodsRouteImport.update({
  id: '/vods',
  path: '/vods',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotRoute = SnapshotRouteImport.update({
  id: '/snapshot',
  path: '/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const RightsRoute = RightsRouteImport.update({
  id: '/rights',
  path: '/rights',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticeRoute = NoticeRouteImport.update({
  id: '/notice',
  path: '/notice',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiviewRoute = MultiviewRouteImport.update({
  id: '/multiview',
  path: '/multiview',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const CafeRoute = CafeRouteImport.update({
  id: '/cafe',
  path: '/cafe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VodsIndexRoute = VodsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VodsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfileCodeRoute = ProfileCodeRouteImport.update({
  id: '/profile/$code',
  path: '/profile/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDiscoverRoute = PlayDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => PlayRoute,
} as any)
const PlayMemberRoute = PlayMemberRouteImport.update({
  id: '/_member',
  getParentRoute: () => PlayRoute,
} as any)
const PlayCatalogRoute = PlayCatalogRouteImport.update({
  id: '/_catalog',
  getParentRoute: () => PlayRoute,
} as any)
const AdminYoutubeCacheRoute = AdminYoutubeCacheRouteImport.update({
  id: '/youtube-cache',
  path: '/youtube-cache',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSnapshotRoute = AdminSnapshotRouteImport.update({
  id: '/snapshot',
  path: '/snapshot',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOtwPlayRoute = AdminOtwPlayRouteImport.update({
  id: '/otw-play',
  path: '/otw-play',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMemberPostsRoute = AdminMemberPostsRouteImport.update({
  id: '/member-posts',
  path: '/member-posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKirinukiRoute = AdminKirinukiRouteImport.update({
  id: '/kirinuki',
  path: '/kirinuki',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDdaysRoute = AdminDdaysRouteImport.update({
  id: '/ddays',
  path: '/ddays',
  getParentRoute: () => AdminRoute,
} as any)
const PlayCatalogIndexRoute = PlayCatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayCatalogRoute,
} as any)
const PlayMemberSubmitRoute = PlayMemberSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => PlayMemberRoute,
} as any)
const PlayMemberSubmissionsRoute = PlayMemberSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => PlayMemberRoute,
} as any)
const PlayCatalogSongsRoute = PlayCatalogSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => PlayCatalogRoute,
} as any)
const PlayCatalogSongsIndexRoute = PlayCatalogSongsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayCatalogSongsRoute,
} as any)
const PlayCatalogSongsSongSlugRoute =
  PlayCatalogSongsSongSlugRouteImport.update({
    id: '/$songSlug',
    path: '/$songSlug',
    getParentRoute: () => PlayCatalogSongsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cafe': typeof CafeRoute
  '/feed': typeof FeedRoute
  '/multiview': typeof MultiviewRoute
  '/notice': typeof NoticeRoute
  '/play': typeof PlayRouteWithChildren
  '/rights': typeof RightsRoute
  '/snapshot': typeof SnapshotRoute
  '/vods': typeof VodsRouteWithChildren
  '/weekly': typeof WeeklyRoute
  '/admin/ddays': typeof AdminDdaysRoute
  '/admin/kirinuki': typeof AdminKirinukiRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/member-posts': typeof AdminMemberPostsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/otw-play': typeof AdminOtwPlayRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/snapshot': typeof AdminSnapshotRoute
  '/admin/youtube-cache': typeof AdminYoutubeCacheRoute
  '/play/discover': typeof PlayDiscoverRoute
  '/profile/$code': typeof ProfileCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/vods/': typeof VodsIndexRoute
  '/play/songs': typeof PlayCatalogSongsRouteWithChildren
  '/play/submissions': typeof PlayMemberSubmissionsRoute
  '/play/submit': typeof PlayMemberSubmitRoute
  '/play/': typeof PlayCatalogIndexRoute
  '/play/songs/$songSlug': typeof PlayCatalogSongsSongSlugRoute
  '/play/songs/': typeof PlayCatalogSongsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cafe': typeof CafeRoute
  '/feed': typeof FeedRoute
  '/multiview': typeof MultiviewRoute
  '/notice': typeof NoticeRoute
  '/play': typeof PlayCatalogIndexRoute
  '/rights': typeof RightsRoute
  '/snapshot': typeof SnapshotRoute
  '/weekly': typeof WeeklyRoute
  '/admin/ddays': typeof AdminDdaysRoute
  '/admin/kirinuki': typeof AdminKirinukiRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/member-posts': typeof AdminMemberPostsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/otw-play': typeof AdminOtwPlayRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/snapshot': typeof AdminSnapshotRoute
  '/admin/youtube-cache': typeof AdminYoutubeCacheRoute
  '/play/discover': typeof PlayDiscoverRoute
  '/profile/$code': typeof ProfileCodeRoute
  '/admin': typeof AdminIndexRoute
  '/vods': typeof VodsIndexRoute
  '/play/submissions': typeof PlayMemberSubmissionsRoute
  '/play/submit': typeof PlayMemberSubmitRoute
  '/play/songs/$songSlug': typeof PlayCatalogSongsSongSlugRoute
  '/play/songs': typeof PlayCatalogSongsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cafe': typeof CafeRoute
  '/feed': typeof FeedRoute
  '/multiview': typeof MultiviewRoute
  '/notice': typeof NoticeRoute
  '/play': typeof PlayRouteWithChildren
  '/rights': typeof RightsRoute
  '/snapshot': typeof SnapshotRoute
  '/vods': typeof VodsRouteWithChildren
  '/weekly': typeof WeeklyRoute
  '/admin/ddays': typeof AdminDdaysRoute
  '/admin/kirinuki': typeof AdminKirinukiRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/member-posts': typeof AdminMemberPostsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/otw-play': typeof AdminOtwPlayRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/snapshot': typeof AdminSnapshotRoute
  '/admin/youtube-cache': typeof AdminYoutubeCacheRoute
  '/play/_catalog': typeof PlayCatalogRouteWithChildren
  '/play/_member': typeof PlayMemberRouteWithChildren
  '/play/discover': typeof PlayDiscoverRoute
  '/profile/$code': typeof ProfileCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/vods/': typeof VodsIndexRoute
  '/play/_catalog/songs': typeof PlayCatalogSongsRouteWithChildren
  '/play/_member/submissions': typeof PlayMemberSubmissionsRoute
  '/play/_member/submit': typeof PlayMemberSubmitRoute
  '/play/_catalog/': typeof PlayCatalogIndexRoute
  '/play/_catalog/songs/$songSlug': typeof PlayCatalogSongsSongSlugRoute
  '/play/_catalog/songs/': typeof PlayCatalogSongsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cafe'
    | '/feed'
    | '/multiview'
    | '/notice'
    | '/play'
    | '/rights'
    | '/snapshot'
    | '/vods'
    | '/weekly'
    | '/admin/ddays'
    | '/admin/kirinuki'
    | '/admin/logs'
    | '/admin/member-posts'
    | '/admin/notices'
    | '/admin/operations'
    | '/admin/otw-play'
    | '/admin/settings'
    | '/admin/snapshot'
    | '/admin/youtube-cache'
    | '/play/discover'
    | '/profile/$code'
    | '/admin/'
    | '/vods/'
    | '/play/songs'
    | '/play/submissions'
    | '/play/submit'
    | '/play/'
    | '/play/songs/$songSlug'
    | '/play/songs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cafe'
    | '/feed'
    | '/multiview'
    | '/notice'
    | '/play'
    | '/rights'
    | '/snapshot'
    | '/weekly'
    | '/admin/ddays'
    | '/admin/kirinuki'
    | '/admin/logs'
    | '/admin/member-posts'
    | '/admin/notices'
    | '/admin/operations'
    | '/admin/otw-play'
    | '/admin/settings'
    | '/admin/snapshot'
    | '/admin/youtube-cache'
    | '/play/discover'
    | '/profile/$code'
    | '/admin'
    | '/vods'
    | '/play/submissions'
    | '/play/submit'
    | '/play/songs/$songSlug'
    | '/play/songs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cafe'
    | '/feed'
    | '/multiview'
    | '/notice'
    | '/play'
    | '/rights'
    | '/snapshot'
    | '/vods'
    | '/weekly'
    | '/admin/ddays'
    | '/admin/kirinuki'
    | '/admin/logs'
    | '/admin/member-posts'
    | '/admin/notices'
    | '/admin/operations'
    | '/admin/otw-play'
    | '/admin/settings'
    | '/admin/snapshot'
    | '/admin/youtube-cache'
    | '/play/_catalog'
    | '/play/_member'
    | '/play/discover'
    | '/profile/$code'
    | '/admin/'
    | '/vods/'
    | '/play/_catalog/songs'
    | '/play/_member/submissions'
    | '/play/_member/submit'
    | '/play/_catalog/'
    | '/play/_catalog/songs/$songSlug'
    | '/play/_catalog/songs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CafeRoute: typeof CafeRoute
  FeedRoute: typeof FeedRoute
  MultiviewRoute: typeof MultiviewRoute
  NoticeRoute: typeof NoticeRoute
  PlayRoute: typeof PlayRouteWithChildren
  RightsRoute: typeof RightsRoute
  SnapshotRoute: typeof SnapshotRoute
  VodsRoute: typeof VodsRouteWithChildren
  WeeklyRoute: typeof WeeklyRoute
  ProfileCodeRoute: typeof ProfileCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly': {
      id: '/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof WeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vods': {
      id: '/vods'
      path: '/vods'
      fullPath: '/vods'
      preLoaderRoute: typeof VodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshot': {
      id: '/snapshot'
      path: '/snapshot'
      fullPath: '/snapshot'
      preLoaderRoute: typeof SnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rights': {
      id: '/rights'
      path: '/rights'
      fullPath: '/rights'
      preLoaderRoute: typeof RightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notice': {
      id: '/notice'
      path: '/notice'
      fullPath: '/notice'
      preLoaderRoute: typeof NoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiview': {
      id: '/multiview'
      path: '/multiview'
      fullPath: '/multiview'
      preLoaderRoute: typeof MultiviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafe': {
      id: '/cafe'
      path: '/cafe'
      fullPath: '/cafe'
      preLoaderRoute: typeof CafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vods/': {
      id: '/vods/'
      path: '/'
      fullPath: '/vods/'
      preLoaderRoute: typeof VodsIndexRouteImport
      parentRoute: typeof VodsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profile/$code': {
      id: '/profile/$code'
      path: '/profile/$code'
      fullPath: '/profile/$code'
      preLoaderRoute: typeof ProfileCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/discover': {
      id: '/play/discover'
      path: '/discover'
      fullPath: '/play/discover'
      preLoaderRoute: typeof PlayDiscoverRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/_member': {
      id: '/play/_member'
      path: ''
      fullPath: '/play'
      preLoaderRoute: typeof PlayMemberRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/_catalog': {
      id: '/play/_catalog'
      path: ''
      fullPath: '/play'
      preLoaderRoute: typeof PlayCatalogRouteImport
      parentRoute: typeof PlayRoute
    }
    '/admin/youtube-cache': {
      id: '/admin/youtube-cache'
      path: '/youtube-cache'
      fullPath: '/admin/youtube-cache'
      preLoaderRoute: typeof AdminYoutubeCacheRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/snapshot': {
      id: '/admin/snapshot'
      path: '/snapshot'
      fullPath: '/admin/snapshot'
      preLoaderRoute: typeof AdminSnapshotRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/otw-play': {
      id: '/admin/otw-play'
      path: '/otw-play'
      fullPath: '/admin/otw-play'
      preLoaderRoute: typeof AdminOtwPlayRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/member-posts': {
      id: '/admin/member-posts'
      path: '/member-posts'
      fullPath: '/admin/member-posts'
      preLoaderRoute: typeof AdminMemberPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kirinuki': {
      id: '/admin/kirinuki'
      path: '/kirinuki'
      fullPath: '/admin/kirinuki'
      preLoaderRoute: typeof AdminKirinukiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ddays': {
      id: '/admin/ddays'
      path: '/ddays'
      fullPath: '/admin/ddays'
      preLoaderRoute: typeof AdminDdaysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/play/_catalog/': {
      id: '/play/_catalog/'
      path: '/'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayCatalogIndexRouteImport
      parentRoute: typeof PlayCatalogRoute
    }
    '/play/_member/submit': {
      id: '/play/_member/submit'
      path: '/submit'
      fullPath: '/play/submit'
      preLoaderRoute: typeof PlayMemberSubmitRouteImport
      parentRoute: typeof PlayMemberRoute
    }
    '/play/_member/submissions': {
      id: '/play/_member/submissions'
      path: '/submissions'
      fullPath: '/play/submissions'
      preLoaderRoute: typeof PlayMemberSubmissionsRouteImport
      parentRoute: typeof PlayMemberRoute
    }
    '/play/_catalog/songs': {
      id: '/play/_catalog/songs'
      path: '/songs'
      fullPath: '/play/songs'
      preLoaderRoute: typeof PlayCatalogSongsRouteImport
      parentRoute: typeof PlayCatalogRoute
    }
    '/play/_catalog/songs/': {
      id: '/play/_catalog/songs/'
      path: '/'
      fullPath: '/play/songs/'
      preLoaderRoute: typeof PlayCatalogSongsIndexRouteImport
      parentRoute: typeof PlayCatalogSongsRoute
    }
    '/play/_catalog/songs/$songSlug': {
      id: '/play/_catalog/songs/$songSlug'
      path: '/$songSlug'
      fullPath: '/play/songs/$songSlug'
      preLoaderRoute: typeof PlayCatalogSongsSongSlugRouteImport
      parentRoute: typeof PlayCatalogSongsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDdaysRoute: typeof AdminDdaysRoute
  AdminKirinukiRoute: typeof AdminKirinukiRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMemberPostsRoute: typeof AdminMemberPostsRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminOperationsRoute: typeof AdminOperationsRoute
  AdminOtwPlayRoute: typeof AdminOtwPlayRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSnapshotRoute: typeof AdminSnapshotRoute
  AdminYoutubeCacheRoute: typeof AdminYoutubeCacheRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDdaysRoute: AdminDdaysRoute,
  AdminKirinukiRoute: AdminKirinukiRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMemberPostsRoute: AdminMemberPostsRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminOperationsRoute: AdminOperationsRoute,
  AdminOtwPlayRoute: AdminOtwPlayRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSnapshotRoute: AdminSnapshotRoute,
  AdminYoutubeCacheRoute: AdminYoutubeCacheRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PlayCatalogSongsRouteChildren {
  PlayCatalogSongsSongSlugRoute: typeof PlayCatalogSongsSongSlugRoute
  PlayCatalogSongsIndexRoute: typeof PlayCatalogSongsIndexRoute
}

const PlayCatalogSongsRouteChildren: PlayCatalogSongsRouteChildren = {
  PlayCatalogSongsSongSlugRoute: PlayCatalogSongsSongSlugRoute,
  PlayCatalogSongsIndexRoute: PlayCatalogSongsIndexRoute,
}

const PlayCatalogSongsRouteWithChildren =
  PlayCatalogSongsRoute._addFileChildren(PlayCatalogSongsRouteChildren)

interface PlayCatalogRouteChildren {
  PlayCatalogSongsRoute: typeof PlayCatalogSongsRouteWithChildren
  PlayCatalogIndexRoute: typeof PlayCatalogIndexRoute
}

const PlayCatalogRouteChildren: PlayCatalogRouteChildren = {
  PlayCatalogSongsRoute: PlayCatalogSongsRouteWithChildren,
  PlayCatalogIndexRoute: PlayCatalogIndexRoute,
}

const PlayCatalogRouteWithChildren = PlayCatalogRoute._addFileChildren(
  PlayCatalogRouteChildren,
)

interface PlayMemberRouteChildren {
  PlayMemberSubmissionsRoute: typeof PlayMemberSubmissionsRoute
  PlayMemberSubmitRoute: typeof PlayMemberSubmitRoute
}

const PlayMemberRouteChildren: PlayMemberRouteChildren = {
  PlayMemberSubmissionsRoute: PlayMemberSubmissionsRoute,
  PlayMemberSubmitRoute: PlayMemberSubmitRoute,
}

const PlayMemberRouteWithChildren = PlayMemberRoute._addFileChildren(
  PlayMemberRouteChildren,
)

interface PlayRouteChildren {
  PlayCatalogRoute: typeof PlayCatalogRouteWithChildren
  PlayMemberRoute: typeof PlayMemberRouteWithChildren
  PlayDiscoverRoute: typeof PlayDiscoverRoute
}

const PlayRouteChildren: PlayRouteChildren = {
  PlayCatalogRoute: PlayCatalogRouteWithChildren,
  PlayMemberRoute: PlayMemberRouteWithChildren,
  PlayDiscoverRoute: PlayDiscoverRoute,
}

const PlayRouteWithChildren = PlayRoute._addFileChildren(PlayRouteChildren)

interface VodsRouteChildren {
  VodsIndexRoute: typeof VodsIndexRoute
}

const VodsRouteChildren: VodsRouteChildren = {
  VodsIndexRoute: VodsIndexRoute,
}

const VodsRouteWithChildren = VodsRoute._addFileChildren(VodsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CafeRoute: CafeRoute,
  FeedRoute: FeedRoute,
  MultiviewRoute: MultiviewRoute,
  NoticeRoute: NoticeRoute,
  PlayRoute: PlayRouteWithChildren,
  RightsRoute: RightsRoute,
  SnapshotRoute: SnapshotRoute,
  VodsRoute: VodsRouteWithChildren,
  WeeklyRoute: WeeklyRoute,
  ProfileCodeRoute: ProfileCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
