/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyRouteImport } from './routes/weekly'
import { Route as VodsRouteImport } from './routes/vods'
import { Route as SnapshotRouteImport } from './routes/snapshot'
import { Route as NoticeRouteImport } from './routes/notice'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VodsIndexRouteImport } from './routes/vods/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileCodeRouteImport } from './routes/profile/$code'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminNoticesRouteImport } from './routes/admin/notices'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminKirinukiRouteImport } from './routes/admin/kirinuki'
import { Route as AdminDdaysRouteImport } from './routes/admin/ddays'

const WeeklyRoute = WeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const VodsRoute = VodsRouteImport.update({
  id: '/vods',
  path: '/vods',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotRoute = SnapshotRouteImport.update({
  id: '/snapshot',
  path: '/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticeRoute = NoticeRouteImport.update({
  id: '/notice',
  path: '/notice',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VodsIndexRoute = VodsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VodsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfileCodeRoute = ProfileCodeRouteImport.update({
  id: '/profile/$code',
  path: '/profile/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKirinukiRoute = AdminKirinukiRouteImport.update({
  id: '/kirinuki',
  path: '/kirinuki',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDdaysRoute = AdminDdaysRouteImport.update({
  id: '/ddays',
  path: '/ddays',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/notice': typeof NoticeRoute
  '/snapshot': typeof SnapshotRoute
  '/vods': typeof VodsRouteWithChildren
  '/weekly': typeof WeeklyRoute
  '/admin/ddays': typeof AdminDdaysRoute
  '/admin/kirinuki': typeof AdminKirinukiRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/profile/$code': typeof ProfileCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/vods/': typeof VodsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notice': typeof NoticeRoute
  '/snapshot': typeof SnapshotRoute
  '/weekly': typeof WeeklyRoute
  '/admin/ddays': typeof AdminDdaysRoute
  '/admin/kirinuki': typeof AdminKirinukiRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/profile/$code': typeof ProfileCodeRoute
  '/admin': typeof AdminIndexRoute
  '/vods': typeof VodsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/notice': typeof NoticeRoute
  '/snapshot': typeof SnapshotRoute
  '/vods': typeof VodsRouteWithChildren
  '/weekly': typeof WeeklyRoute
  '/admin/ddays': typeof AdminDdaysRoute
  '/admin/kirinuki': typeof AdminKirinukiRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/profile/$code': typeof ProfileCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/vods/': typeof VodsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/notice'
    | '/snapshot'
    | '/vods'
    | '/weekly'
    | '/admin/ddays'
    | '/admin/kirinuki'
    | '/admin/logs'
    | '/admin/notices'
    | '/admin/settings'
    | '/profile/$code'
    | '/admin/'
    | '/vods/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notice'
    | '/snapshot'
    | '/weekly'
    | '/admin/ddays'
    | '/admin/kirinuki'
    | '/admin/logs'
    | '/admin/notices'
    | '/admin/settings'
    | '/profile/$code'
    | '/admin'
    | '/vods'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/notice'
    | '/snapshot'
    | '/vods'
    | '/weekly'
    | '/admin/ddays'
    | '/admin/kirinuki'
    | '/admin/logs'
    | '/admin/notices'
    | '/admin/settings'
    | '/profile/$code'
    | '/admin/'
    | '/vods/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  NoticeRoute: typeof NoticeRoute
  SnapshotRoute: typeof SnapshotRoute
  VodsRoute: typeof VodsRouteWithChildren
  WeeklyRoute: typeof WeeklyRoute
  ProfileCodeRoute: typeof ProfileCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly': {
      id: '/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof WeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vods': {
      id: '/vods'
      path: '/vods'
      fullPath: '/vods'
      preLoaderRoute: typeof VodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshot': {
      id: '/snapshot'
      path: '/snapshot'
      fullPath: '/snapshot'
      preLoaderRoute: typeof SnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notice': {
      id: '/notice'
      path: '/notice'
      fullPath: '/notice'
      preLoaderRoute: typeof NoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vods/': {
      id: '/vods/'
      path: '/'
      fullPath: '/vods/'
      preLoaderRoute: typeof VodsIndexRouteImport
      parentRoute: typeof VodsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profile/$code': {
      id: '/profile/$code'
      path: '/profile/$code'
      fullPath: '/profile/$code'
      preLoaderRoute: typeof ProfileCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kirinuki': {
      id: '/admin/kirinuki'
      path: '/kirinuki'
      fullPath: '/admin/kirinuki'
      preLoaderRoute: typeof AdminKirinukiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ddays': {
      id: '/admin/ddays'
      path: '/ddays'
      fullPath: '/admin/ddays'
      preLoaderRoute: typeof AdminDdaysRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDdaysRoute: typeof AdminDdaysRoute
  AdminKirinukiRoute: typeof AdminKirinukiRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDdaysRoute: AdminDdaysRoute,
  AdminKirinukiRoute: AdminKirinukiRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface VodsRouteChildren {
  VodsIndexRoute: typeof VodsIndexRoute
}

const VodsRouteChildren: VodsRouteChildren = {
  VodsIndexRoute: VodsIndexRoute,
}

const VodsRouteWithChildren = VodsRoute._addFileChildren(VodsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  NoticeRoute: NoticeRoute,
  SnapshotRoute: SnapshotRoute,
  VodsRoute: VodsRouteWithChildren,
  WeeklyRoute: WeeklyRoute,
  ProfileCodeRoute: ProfileCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
